---

- name: Set default secret fact
  set_fact:
    secret: "{{ secret_item }}"

- name: Fail for Missing name, files
  fail: msg="This role requires secret.name and secret.files to be set"
  when: secret.name is not defined and secret.files is not defined

- name: Set basic secret Facts
  set_fact:
    secret_args: ''

- name: Set secret overwrite to False if not set
  set_fact:
    secret_overwrite: False
  when: secret.overwrite is not defined

- name: Set secret overwrite to True if set
  set_fact:
    secret_overwrite: True
  when: secret.overwrite is defined

- name: Build secrets args
  with_items: '{{ secret.files }}'
  set_fact:
    secret_args: "{{ secret_args }} {{ item }}"

- name: "Determine if secret '{{ secret.name }}' exists"
  command: >
     {{ openshift.common.client_binary }} get secret {{ secret.name }} -n {{ project.name }} -o json
  register: get_secret_result
  failed_when: false
  changed_when: false

- name: "Delete secret so we can re-create it if overwrite is True"
  command: >
    {{ openshift.common.client_binary }} delete secret {{ secret.name }} -n {{ project.name }}
  when: get_secret_result.rc == 0 and secret_overwrite

- name: Create Secret
  command: >
    {{ openshift.common.client_binary }} secrets new {{ secret.name }} {{ secret_args }} -n {{ project.name }}
  when: get_secret_result.rc != 0 or secret_overwrite

- name: Link secret to service accounts
  command: >
    {{ openshift.common.client_binary }} secrets link {{ item }} {{ secret.name }} -n {{ project.name }}
  with_items: '{{ secret.link_to_serviceaccounts }}'
  when: secret.link_to_serviceaccounts is defined
