---

- name: Set default secret fact
  set_fact:
    secret: "{{ secret_item }}"

- name: Fail for Missing name, files
  fail: msg="This role requires secret.name and secret.files to be set"
  when: secret.name is not defined and secret.files is not defined

- name: Set basic secret Facts
  set_fact:
    secret_args: ''

- name: Build secrets args
  with_items: '{{ secret.files }}'
  set_fact:
    secret_args: "{{ secret_args }} {{ item }}"

- name: "Determine if secret '{{ secret.name }}' exists"
  command: >
     {{ openshift.common.client_binary }} get secret {{ secret.name }} -n {{ project.name }} -o json
  register: get_secret_result
  failed_when: false
  changed_when: false

- name: Create Secret
  command: >
    {{ openshift.common.client_binary }} secrets new {{ secret.name }} {{ secret_args }}
  when: get_secret_result.rc == 1

- name: Link secret to service accounts
  command: >
    {{ openshift.common.client_binary }} secrets link {{ item }} {{ secret.name }}
  with_items: '{{ secret.link_to_serviceaccounts }}'
  when: secret.link_to_serviceaccounts is defined
