---
- name: "Prepare for the Launch of the InfoGraphics Demo"
  hosts: localhost
  roles:
  - role: openshift-defaults
  tasks:
  - name: Prepare Resource File
    template:
      src: roles/launch-infographic-demo/templates/demo_resources.j2
      dest: /tmp/{{ openshift_project_name }}_resources.json

- name: "Create and Launch the InfoGraphics Demo"
  hosts: localhost
  pre_tasks:
  - include_vars: /tmp/{{ openshift_project_name }}_resources.json
  vars:
  - seed_job_name: Seed_Project_Release_Pipeline
  - jenkins_user: "{{ jenkins_user }}"
  - jenkins_password: "{{ jenkins_password }}"
  - jenkins_token: "{{ jenkins_token }}"
  roles:
  - role: openshift-defaults
  - role: create-openshift-resources
#  - role: launch-hexboard-demo

- name: "Clean-Up"
  hosts: localhost
  tasks:
  - name: Remove Resource File
    shell: rm -f /tmp/{{ openshift_project_name }}_resources.json
