---
- name: "Log in to OpenShift Client"
  command: >
    {{ openshift.common.client_binary }} login {{ openshift_host_env }} 
    --insecure-skip-tls-verify=true --username={{ openshift_user }} --password={{ openshift_password }}
  changed_when: False

- name: "Echo Whoami"
  command: >
    {{ openshift.common.client_binary }} whoami   
  changed_when: False

- name: "Obtain User Token"
  command: >
    {{ openshift.common.client_binary }} whoami -t
  register: openshift_access_token 
  when: openshift_access_token is not defined or openshift_access_token == ''

