---
- name: "Create Demo Pipeline"
  uri:
    url: https://{{ jenkins_user }}:{{ jenkins_token }}@{{ jenkins_host_env }}/job/{{ seed_job_name }}/buildWithParameters?token=rhoil&new_job_name={{ openshift_project_name }}&git_url={{ git_url|urlencode() }}&git_branch={{ git_branch }}
    method: POST
    force_basic_auth: yes
    validate_certs: no
    status_code: 201
